package ZhiJianHu.Common;

/**
 * @author 胡志坚
 * @version 1.0
 * 创造日期 2024/12/14
 * 说明:信息类型
 */
public enum MessageType {
    MESSAGE_LOGIN_MES,
    MESSAGE_LOGIN_SUCCEED,//登录成功
    MESSAGE_LOGIN_FAILED,//登陆失败
    MESSAGE_PRIVATE_MES,
    MESSAGE_ALL_MES,
    MESSAGE_SHOW_USER,
    MESSAGE_ADD_USER,
    MESSAGE_SEND_FILE,
    MESSAGE_PRIVATE_FILE,
    MESSAGE_EXIT_MES,
    MESSAGE_OPEN_MES,
    MESSAGE_REGISTER,
    MESSAGE_REGISTER_SUCCEED,
    MESSAGE_REGISTER_FILE,
    MESSAGE_USER_DATA,
}
